"""Export the per-game mods.db knowledge bases into an Obsidian web.

Generates Prometheus_Master/08_OBSIDIAN/ — one note per mod, address,
finding-topic, bad-path list and (Tenchu) character slot, all wikilinked so
Obsidian's graph view acts as the project context web.

Idempotent: everything under 08_OBSIDIAN except _notes/ is regenerated on
each run. Put hand-written commentary in _notes/ and wikilink it; it is
never touched.

Usage:  python obsidian_export.py
"""

import json
import re
import shutil
import sqlite3
import time
from pathlib import Path

MASTER = Path(__file__).resolve().parent.parent
OUT = MASTER / "08_OBSIDIAN"

GAMES = {
    "SLUS-20407": {
        "title": "Way of the Samurai",
        "db": MASTER / "01_GAMES" / "SLUS-20407_WayOfTheSamurai" / "db" / "mods.db",
    },
    "SLUS-20397": {
        "title": "Tenchu Wrath of Heaven",
        "db": MASTER / "01_GAMES" / "SLUS-20397_Tenchu" / "db" / "mods.db",
    },
}

BANNER = "> [!info] AUTO-GENERATED by 03_TOOLS/obsidian_export.py — edits here are overwritten. Hand-written notes go in `08_OBSIDIAN/_notes/`.\n\n"


def slug(text: str, maxlen: int = 80) -> str:
    s = re.sub(r"[^\w\s-]", "", str(text)).strip()
    s = re.sub(r"[\s]+", " ", s)
    return s[:maxlen].strip() or "untitled"


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(BANNER + body, encoding="utf-8")


def get(row, key, default=None):
    return row[key] if key in row.keys() else default


def rows(conn, query, params=()):
    conn.row_factory = sqlite3.Row
    try:
        return conn.execute(query, params).fetchall()
    except sqlite3.OperationalError:
        return []


def export_game(serial: str, meta: dict) -> str:
    """Returns the wikilink to the game hub note."""
    title = meta["title"]
    gdir = OUT / serial
    conn = sqlite3.connect(str(meta["db"]))

    # ---- mods ----
    mod_links = []
    for m in rows(conn, "SELECT * FROM km_mod_manifest ORDER BY name"):
        name = slug(m["name"])
        addrs = ""
        try:
            addr_list = json.loads(get(m, "addresses") or "[]")
            addrs = ", ".join(
                f"[[{serial} addr {a}]]" if isinstance(a, str) else f"[[{serial} addr 0x{a:08X}]]"
                for a in addr_list
            )
        except Exception:
            addrs = str(get(m, "addresses") or "")
        body = (
            f"# {get(m, 'name', '')}\n\n"
            f"- **Game**: [[{serial} {title}]]\n"
            f"- **Status**: `{get(m, 'status', '')}`\n"
            f"- **Category**: {get(m, 'category', '')}\n"
            f"- **Mechanism**: {get(m, 'mechanism', '') or '—'}\n"
            f"- **Addresses**: {addrs or '—'}\n"
            f"- **Toggle**: `{get(m, 'toggle_path', '') or '—'}`\n\n"
            f"{get(m, 'notes', '') or ''}\n"
        )
        write(gdir / "mods" / f"{serial} mod {name}.md", body)
        mod_links.append(f"- [[{serial} mod {name}]] — `{str(get(m, 'status', ''))[:40]}`")

    # ---- addresses ----
    addr_links = []
    for a in rows(conn, "SELECT * FROM km_addresses ORDER BY category, label"):
        hexaddr = f"0x{a['address']:08X}"
        name = f"{serial} addr {hexaddr}"
        body = (
            f"# {get(a, 'label', '')} @ {hexaddr}\n\n"
            f"- **Game**: [[{serial} {title}]]\n"
            f"- **Category**: [[{serial} category {slug(get(a, 'category', '') or 'uncategorized')}]]\n"
            f"- **Format**: `{get(a, 'fmt', '') or '?'}`\n\n"
            f"{get(a, 'notes', '') or ''}\n"
        )
        write(gdir / "addresses" / f"{name}.md", body)
        addr_links.append((a["category"] or "uncategorized", f"- [[{name}]] — {get(a, 'label', '')}"))

    cats = {}
    for cat, link in addr_links:
        cats.setdefault(cat, []).append(link)
    for cat, links in cats.items():
        write(
            gdir / "addresses" / f"{serial} category {slug(cat)}.md",
            f"# {title} — {cat} addresses\n\nGame: [[{serial} {title}]]\n\n" + "\n".join(links) + "\n",
        )

    # ---- findings grouped by topic ----
    topics = {}
    for f in rows(conn, "SELECT * FROM km_findings ORDER BY ts"):
        topics.setdefault(get(f, "topic", "misc"), []).append(f)
    for f in rows(conn, "SELECT * FROM km_re_findings ORDER BY id"):
        key = get(f, "topic", "misc") if "topic" in f.keys() else "re_findings"
        topics.setdefault(key, []).append(f)
    topic_links = []
    for topic, items in topics.items():
        name = f"{serial} topic {slug(topic)}"
        lines = [f"# {topic}\n", f"Game: [[{serial} {title}]]\n"]
        for f in items:
            ts = ""
            try:
                ts = time.strftime("%Y-%m-%d", time.localtime(get(f, "ts", 0)))
            except Exception:
                pass
            outcome = f["outcome"] if "outcome" in f.keys() else ""
            details = f["details"] if "details" in f.keys() else str(dict(f))
            lines.append(f"- **{ts} {outcome}** — {details}")
        write(gdir / "findings" / f"{name}.md", "\n".join(lines) + "\n")
        topic_links.append(f"- [[{name}]] ({len(items)})")

    # ---- bad paths (one hub note) ----
    bp = []
    for b in rows(conn, "SELECT * FROM km_bad_paths"):
        keys = b.keys()
        what = b["topic"] if "topic" in keys else (b["pattern"] if "pattern" in keys else "?")
        why = b["why_failed"] if "why_failed" in keys else (b["reason"] if "reason" in keys else "")
        bp.append(f"- ❌ **{what}** — {why}")
    write(
        gdir / f"{serial} DO NOT RETRY.md",
        f"# {title} — known-bad paths\n\nGame: [[{serial} {title}]]\n\n" + "\n".join(bp) + "\n",
    )

    # ---- Tenchu character slots ----
    char_links = []
    for c in rows(conn, "SELECT * FROM km_characters ORDER BY id"):
        d = dict(c)
        label = slug(d.get("name") or d.get("label") or f"slot {d.get('slot', d.get('id'))}")
        name = f"{serial} char {label}"
        fields = "\n".join(f"- **{k}**: `{v}`" for k, v in d.items() if v is not None)
        write(
            gdir / "characters" / f"{name}.md",
            f"# {label}\n\nGame: [[{serial} {title}]]\n\n{fields}\n",
        )
        char_links.append(f"- [[{name}]]")

    # ---- game hub ----
    hub = [
        f"# {title} ({serial})\n",
        "Part of [[Prometheus Map]].\n",
        f"## Mods ({len(mod_links)})",
        *mod_links,
        f"\n## Finding topics ({len(topic_links)})",
        *topic_links,
        f"\n## Address categories ({len(cats)})",
        *[f"- [[{serial} category {slug(c)}]] ({len(l)})" for c, l in cats.items()],
        f"\n## Known-bad paths",
        f"- [[{serial} DO NOT RETRY]]",
    ]
    if char_links:
        hub += [f"\n## Characters ({len(char_links)})", *char_links]
    write(gdir / f"{serial} {title}.md", "\n".join(hub) + "\n")
    conn.close()
    return f"[[{serial} {title}]]"


def main():
    if OUT.exists():
        for child in OUT.iterdir():
            if child.name == "_notes":
                continue
            shutil.rmtree(child) if child.is_dir() else child.unlink()
    (OUT / "_notes").mkdir(parents=True, exist_ok=True)

    game_links = [export_game(serial, meta) for serial, meta in GAMES.items()]
    write(
        OUT / "Prometheus Map.md",
        "# Prometheus — project map\n\n"
        "The DB-backed context web. Regenerate with `python 03_TOOLS/obsidian_export.py`.\n\n"
        "## Games\n" + "\n".join(f"- {g}" for g in game_links) + "\n\n"
        "## Living documents (outside this generated web)\n"
        "- [[progress]] — day-by-day source of truth (05_SESSIONS/progress.md)\n"
        "- 00_README/README.md — folder map\n"
        "- _notes/ — your hand-written notes (never overwritten)\n",
    )
    print(f"Exported to {OUT}")


if __name__ == "__main__":
    main()
