import json
import sqlite3
import threading
import time
from pathlib import Path
from qt_compat import QObject, Signal

from backend.cheat_fetcher import fetch_pcsx2_cheats, parse_pnach


class CheatDB:
    def __init__(self, path="data/cheats.db"):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.conn = sqlite3.connect(str(self.path), check_same_thread=False)
        self.conn.row_factory = sqlite3.Row
        self.lock = threading.Lock()
        self.conn.execute("""
        CREATE TABLE IF NOT EXISTS cheats(
            id TEXT PRIMARY KEY,
            game_crc TEXT NOT NULL,
            title TEXT NOT NULL,
            operations TEXT NOT NULL,
            source TEXT NOT NULL,
            enabled INTEGER NOT NULL DEFAULT 0,
            imported_at REAL NOT NULL
        )
        """)
        self.conn.commit()

    def import_cheat(self, game_crc, cheat):
        cheat_id = f"{game_crc}:{cheat['title'].lower().replace(' ', '_')}"
        with self.lock:
            self.conn.execute(
                "INSERT OR REPLACE INTO cheats(id,game_crc,title,operations,source,imported_at) VALUES(?,?,?,?,?,?)",
                (cheat_id, game_crc, cheat["title"], json.dumps(cheat["operations"]),
                 cheat.get("source", "unknown"), time.time()),
            )
            self.conn.commit()
        return cheat_id

    def list_cheats(self, game_crc):
        with self.lock:
            rows = self.conn.execute("SELECT * FROM cheats WHERE game_crc=? ORDER BY title", (game_crc,)).fetchall()
        data = [dict(r) for r in rows]
        for row in data:
            row["operations"] = json.loads(row["operations"])
        return data

    def set_enabled(self, cheat_id, enabled):
        with self.lock:
            self.conn.execute("UPDATE cheats SET enabled=? WHERE id=?", (int(enabled), cheat_id))
            self.conn.commit()

    def get(self, cheat_id):
        with self.lock:
            row = self.conn.execute("SELECT * FROM cheats WHERE id=?", (cheat_id,)).fetchone()
        if not row:
            return None
        data = dict(row)
        data["operations"] = json.loads(data["operations"])
        return data


class CheatConverter:
    pnach_to_internal = staticmethod(parse_pnach)

    @staticmethod
    def internal_to_pnach(cheats, game_crc="UNKNOWN"):
        lines = [f"// PNACH generated by PS2 Forge Station for {game_crc}"]
        for cheat in cheats:
            lines.append(f"// {cheat['title']}")
            for op in cheat.get("operations", []):
                addr = op["address"].replace("0x", "").upper().zfill(8)
                value = int(op["value"]) & 0xFFFFFFFF
                width = int(op.get("width", 4))
                ptype = {1: "0", 2: "1", 4: "extended"}.get(width, "extended")
                lines.append(f"patch=1,EE,{addr},{ptype},{value:08X}")
        return "\n".join(lines) + "\n"


class CheatHub(QObject):
    cheat_imported = Signal(str)
    cheat_toggled = Signal(str, bool)
    trainer_updated = Signal()

    def __init__(self, pine_proxy=None, data_controller=None, db=None, texture_pack_manager=None,
                 model_swap_manager=None, reference_catalog=None):
        super().__init__()
        self.pine_proxy = pine_proxy
        self.data_controller = data_controller
        self.db = db or CheatDB()
        self.texture_pack_manager = texture_pack_manager
        self.model_swap_manager = model_swap_manager
        self.reference_catalog = reference_catalog
        self._freeze_handles = {}

    def auto_import(self, crc):
        result = fetch_pcsx2_cheats(crc)
        if isinstance(result, dict) and result.get("error"):
            return result
        imported = []
        for cheat in result:
            cheat.setdefault("source", "pcsx2_patches")
            cheat_id = self.db.import_cheat(crc, cheat)
            imported.append(cheat_id)
            if self.data_controller:
                self.data_controller.import_cheat({"id": cheat_id, **cheat, "game_crc": crc})
            self.cheat_imported.emit(cheat_id)
        self.trainer_updated.emit()
        return imported

    def get_trainer_list(self, game_crc):
        return self.db.list_cheats(game_crc)

    def get_trainer_items(self, game_crc):
        items = []
        for cheat in self.db.list_cheats(game_crc):
            items.append({
                "id": cheat["id"],
                "title": cheat["title"],
                "kind": "cheat",
                "enabled": bool(cheat.get("enabled")),
                "source": cheat.get("source", "unknown"),
            })
        if self.texture_pack_manager:
            for pack in self.texture_pack_manager.list_packs(game_crc):
                items.append({
                    "id": pack["id"],
                    "title": pack["name"],
                    "kind": "texture_pack",
                    "enabled": bool(pack.get("enabled")),
                    "source": pack.get("source_url") or "local",
                    "trusted": bool(pack.get("trusted")),
                    "file_count": pack.get("file_count", 0),
                })
        if self.model_swap_manager:
            for swap in self.model_swap_manager.list_swaps(game_crc):
                items.append({
                    "id": swap["id"],
                    "title": swap["name"],
                    "kind": "model_swap",
                    "enabled": bool(swap.get("enabled")),
                    "source": swap.get("source_url") or "local",
                    "file_count": swap.get("file_count", 0),
                    "apply_strategy": swap.get("apply_strategy", "adapter_required"),
                })
        if self.reference_catalog:
            for ref in self.reference_catalog.list_references():
                items.append({
                    "id": ref["id"],
                    "title": ref["title"],
                    "kind": "reference",
                    "enabled": False,
                    "source": ref.get("url", ""),
                    "installable": False,
                    "notes": ref.get("notes", ""),
                })
        return items

    def enable_item(self, item_id, kind, game_crc=None, restart=False):
        if kind == "texture_pack":
            if not self.texture_pack_manager:
                return False
            self.texture_pack_manager.apply_pack(item_id, game_crc, restart=restart)
            self.trainer_updated.emit()
            return True
        if kind == "model_swap":
            if not self.model_swap_manager:
                return False
            self.model_swap_manager.apply_swap(item_id, game_crc, restart=restart)
            self.trainer_updated.emit()
            return True
        if kind == "reference":
            raise RuntimeError("Reference entries are not installable. Add the creator's pack files or download link first.")
        return self.enable_cheat(item_id)

    def disable_item(self, item_id, kind, game_crc=None, restart=False):
        if kind == "texture_pack":
            if not self.texture_pack_manager:
                return False
            self.texture_pack_manager.disable_pack(item_id, game_crc, restart=restart)
            self.trainer_updated.emit()
            return True
        if kind == "model_swap":
            if not self.model_swap_manager:
                return False
            self.model_swap_manager.disable_swap(item_id, game_crc, restart=restart)
            self.trainer_updated.emit()
            return True
        return self.disable_cheat(item_id)

    def enable_cheat(self, cheat_id):
        cheat = self.db.get(cheat_id)
        if not cheat or not self.pine_proxy:
            return False
        handles = []
        for op in cheat["operations"]:
            addr = int(op["address"], 16)
            handles.append(self.pine_proxy.start_freeze(addr, op["value"], op.get("width", 4)))
        self._freeze_handles[cheat_id] = handles
        self.db.set_enabled(cheat_id, True)
        self.cheat_toggled.emit(cheat_id, True)
        return True

    def disable_cheat(self, cheat_id):
        for handle in self._freeze_handles.pop(cheat_id, []):
            self.pine_proxy.stop_freeze(handle)
        self.db.set_enabled(cheat_id, False)
        self.cheat_toggled.emit(cheat_id, False)
        return True

    def export_pnach(self, game_crc):
        return CheatConverter.internal_to_pnach(self.db.list_cheats(game_crc), game_crc)
