"""
Tenchu: Wrath of Heaven character-swap launcher.

Single-window Tkinter app for picking a character bundle, optionally locking
HP / removing letterboxes / motion blur, and launching PCSX2.

Reads:
  - CHARA.BIN (live MDSP scan, so any rebuild updates the list)
Writes:
  - C:\\Users\\owner\\Documents\\PCSX2\\cheats\\SLUS-20397_767E383D.pnach
Launches:
  - C:\\Program Files\\PCSX2\\pcsx2-qt.exe with the Tenchu ISO in fullscreen
"""

import re
import subprocess
import threading
import tkinter as tk
import webbrowser
from pathlib import Path
from tkinter import ttk, messagebox

import sys as _sys
_sys.path.insert(0, str(Path(__file__).parent))
from bundle_names import resolve_names, label_for, VERIFIED, VERIFIED_SIZES  # noqa: E402

CHARA_BIN = Path(r"C:\Users\owner\pcsx2_modder\iso_extracted\ARC\CHARA.BIN")
ISO = Path(r"C:\Emulation\PS2_Games\Tenchu - Wrath of Heaven (USA) (En,Ja).iso")
PCSX2 = Path(r"C:\Program Files\PCSX2\pcsx2-qt.exe")
PNACH_DIR = Path(r"C:\Users\owner\Documents\PCSX2\cheats")
PNACH_FILE = PNACH_DIR / "SLUS-20397_767E383D.pnach"
CHARA_BROWSER = Path(r"C:\Users\owner\Desktop\prometheus\3d_export\SLUS-20397\textures\CHARA_bundles")

KNOWN_NAMES = {off: name for off, (name, _) in VERIFIED.items()}

# Voice override codes (addiu $a0,$zero,N). Default Rikimaru = leave at 0.
VOICE_PRESETS = {
    "Default (unpatched)": None,
    "Ayame Kunoichi voice (3)": 0x24040003,
    "Ayame Kagura voice (9)": 0x24040009,
}

# Daemons to ensure are dead before launch (they break menu input per saved memory)
DAEMON_NAMES = ("items_keeper.py", "autoswap.py", "snapshot_watchdog.py",
                "state_change_watcher.py", "freeze_daemon.py")


def find_iso() -> Path | None:
    candidates = [
        ISO,
        Path(r"C:\Emulation\PS2_Games"),
    ]
    for p in candidates:
        if p.is_file() and p.suffix.lower() in (".iso", ".bin", ".cso"):
            return p
        if p.is_dir():
            for f in p.iterdir():
                if f.suffix.lower() in (".iso", ".bin", ".cso") and "tenchu" in f.name.lower():
                    return f
    return None


def list_bundles() -> list[tuple[int, int, int]]:
    """Return list of (idx, offset, size) for every MDSP in CHARA.BIN."""
    data = CHARA_BIN.read_bytes()
    sz = len(data)
    positions = []
    i = 0
    while True:
        i = data.find(b"MDSP", i)
        if i < 0:
            break
        positions.append(i)
        i += 4
    positions.append(sz)
    return [(idx, positions[idx], positions[idx + 1] - positions[idx])
            for idx in range(len(positions) - 1)]


def write_pnach(bundle: tuple[int, int, int] | None, hp_lock: bool, no_blur: bool,
                no_letterbox: bool, voice_code: int | None):
    PNACH_DIR.mkdir(parents=True, exist_ok=True)
    lines = ["gametitle=Tenchu 3 - Wrath of heaven (NTSC-U) [SLUS-20397]",
             "// Generated by tenchu_launcher.py — applies one character swap + selected utility patches.",
             ""]

    if no_blur:
        lines.extend([
            "[Remove blur effects]",
            "patch=1,EE,20155D3C,word,1000001C",
            "patch=1,EE,20155D90,word,10000022",
            "patch=1,EE,20246180,word,10000003",
            "",
        ])
    if no_letterbox:
        lines.extend([
            "[Remove letterboxes]",
            "patch=1,EE,2024619C,word,10000009",
            "",
        ])
    if hp_lock:
        # PLACEHOLDER — Tenchu HP address not yet RE'd. User will see this code in the
        # cheats panel but it patches nothing real until we replace these with the real
        # address. See "Find Tenchu WoH HP lock pnach" task.
        lines.extend([
            "[HP Lock - PLACEHOLDER, address pending RE]",
            "// TODO: replace with snapshot-diff-verified HP address",
            "",
        ])
    if bundle is not None:
        idx, off, gap_size = bundle
        # Use Techiesaru's exact published size for verified entries; otherwise fall
        # back to MDSP-gap which may include trailing pad.
        actual_size = VERIFIED_SIZES.get(off, gap_size)
        name = KNOWN_NAMES.get(off, f"Bundle {idx:03d}")
        size_note = "verified" if off in VERIFIED_SIZES else "gap-heuristic"
        lines.extend([
            f"[Char swap - {name} (bundle {idx:03d})]",
            f"// NOTE: Techiesaru's verified codes target the VS-Mode Kunoichi slot,",
            f"// not the story-mode Rikimaru/Ayame/Tesshu slot. To see the swap, go",
            f"// to Versus / Multi-player mode and select Kunoichi.",
            f"// offset=0x{off:08x} size=0x{actual_size:x} ({size_note})",
            f"patch=1,EE,204330D0,extended,{off:08X}",
            f"patch=1,EE,204330D4,extended,{actual_size:08X}",
            "",
        ])
    if voice_code is not None:
        lines.extend([
            f"[Voice override]",
            f"patch=1,EE,202D0F00,extended,{voice_code:08X}",
            "",
        ])

    PNACH_FILE.write_text("\n".join(lines), encoding="utf-8")


def kill_daemons() -> list[str]:
    """Force-kill any WoS-style daemons that would block menu input."""
    killed = []
    try:
        out = subprocess.check_output(
            ["wmic", "process", "where",
             "(name='python.exe' or name='pythonw.exe')", "get",
             "ProcessId,CommandLine", "/format:csv"],
            text=True, stderr=subprocess.DEVNULL, timeout=10,
        )
    except Exception:
        return killed
    for line in out.splitlines():
        for name in DAEMON_NAMES:
            if name in line:
                parts = [p for p in line.split(",") if p.strip()]
                if not parts:
                    continue
                pid = parts[-1].strip()
                if pid.isdigit():
                    try:
                        subprocess.run(["taskkill", "/F", "/PID", pid],
                                       check=False, capture_output=True, timeout=5)
                        killed.append(f"{name} (PID {pid})")
                    except Exception:
                        pass
                break
    return killed


def launch_pcsx2(iso: Path):
    subprocess.Popen([str(PCSX2), "-fullscreen", str(iso)], close_fds=True)


class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Tenchu: Wrath of Heaven — Character Swap Launcher")
        self.geometry("680x560")
        self.configure(bg="#1f1f1f")

        try:
            self.bundles = list_bundles()
        except Exception as e:
            messagebox.showerror("CHARA.BIN read failed", str(e))
            self.destroy()
            return

        self.iso_path = find_iso()

        self._build_ui()

    def _build_ui(self):
        pad = {"padx": 14, "pady": 6}

        title = tk.Label(self, text="Tenchu: Wrath of Heaven", bg="#1f1f1f",
                         fg="#7af", font=("Segoe UI", 16, "bold"))
        title.pack(anchor="w", padx=14, pady=(14, 0))
        sub = tk.Label(self, text="SLUS-20397   ·   CHARA.BIN bundle swap (Techiesaru method)",
                       bg="#1f1f1f", fg="#888", font=("Segoe UI", 9))
        sub.pack(anchor="w", padx=14, pady=(0, 8))

        # Character dropdown
        char_frame = tk.LabelFrame(self, text="  Character bundle  ", bg="#1f1f1f", fg="#eee",
                                   font=("Segoe UI", 10, "bold"), bd=1)
        char_frame.pack(fill="x", **pad)

        names = resolve_names()
        options = ["(no swap — default Rikimaru / Ayame / Tesshu)"]
        for idx, off, size in self.bundles:
            options.append(label_for(idx, off, size, names))
        self.bundle_var = tk.StringVar(value=options[0])
        self.bundle_dd = ttk.Combobox(char_frame, textvariable=self.bundle_var,
                                      values=options, state="readonly", width=80)
        self.bundle_dd.pack(fill="x", padx=10, pady=8)

        btn_row = tk.Frame(char_frame, bg="#1f1f1f")
        btn_row.pack(fill="x", padx=10, pady=(0, 8))
        tk.Button(btn_row, text="Preview textures in browser", command=self.preview_bundle,
                  bg="#365", fg="white", relief="flat", padx=10).pack(side="left")
        tk.Button(btn_row, text="Open full bundle map", command=self.open_map,
                  bg="#444", fg="white", relief="flat", padx=10).pack(side="left", padx=(6, 0))

        # Utility toggles
        util = tk.LabelFrame(self, text="  Utility patches  ", bg="#1f1f1f", fg="#eee",
                             font=("Segoe UI", 10, "bold"), bd=1)
        util.pack(fill="x", **pad)
        self.no_blur = tk.BooleanVar(value=True)
        self.no_letterbox = tk.BooleanVar(value=True)
        self.hp_lock = tk.BooleanVar(value=False)
        tk.Checkbutton(util, text="Remove motion blur", variable=self.no_blur,
                       bg="#1f1f1f", fg="#eee", selectcolor="#222",
                       activebackground="#1f1f1f").pack(anchor="w", padx=10)
        tk.Checkbutton(util, text="Remove letterboxes", variable=self.no_letterbox,
                       bg="#1f1f1f", fg="#eee", selectcolor="#222",
                       activebackground="#1f1f1f").pack(anchor="w", padx=10)
        tk.Checkbutton(util, text="HP lock (PLACEHOLDER — address not yet RE'd)",
                       variable=self.hp_lock, bg="#1f1f1f", fg="#aaa", selectcolor="#222",
                       activebackground="#1f1f1f").pack(anchor="w", padx=10)

        # Voice
        voice_frame = tk.LabelFrame(self, text="  Voice override  ", bg="#1f1f1f", fg="#eee",
                                    font=("Segoe UI", 10, "bold"), bd=1)
        voice_frame.pack(fill="x", **pad)
        self.voice_var = tk.StringVar(value="Default (unpatched)")
        ttk.Combobox(voice_frame, textvariable=self.voice_var,
                     values=list(VOICE_PRESETS.keys()), state="readonly",
                     width=40).pack(padx=10, pady=8, anchor="w")

        # Status box
        self.status = tk.Text(self, height=8, bg="#111", fg="#9cf", relief="flat",
                              font=("Consolas", 9))
        self.status.pack(fill="both", expand=True, padx=14, pady=(8, 0))
        self.log(f"CHARA.BIN: {len(self.bundles)} bundles loaded")
        self.log(f"ISO: {self.iso_path if self.iso_path else '⚠ NOT FOUND — set ISO path in script'}")
        self.log(f"pnach output: {PNACH_FILE}")

        # Action row
        act = tk.Frame(self, bg="#1f1f1f")
        act.pack(fill="x", padx=14, pady=12)
        tk.Button(act, text="Apply patch only (no launch)", command=self.apply_only,
                  bg="#444", fg="white", relief="flat", padx=14, pady=6).pack(side="left")
        tk.Button(act, text="Revert to baseline", command=self.revert,
                  bg="#622", fg="white", relief="flat", padx=14, pady=6).pack(side="left", padx=(6, 0))
        tk.Button(act, text="▶  Apply + Launch PCSX2", command=self.apply_and_launch,
                  bg="#284", fg="white", relief="flat", padx=18, pady=6,
                  font=("Segoe UI", 10, "bold")).pack(side="right")

    def log(self, msg: str):
        self.status.insert("end", msg + "\n")
        self.status.see("end")
        self.update_idletasks()

    def selected_bundle(self) -> tuple[int, int, int] | None:
        s = self.bundle_var.get()
        m = re.match(r"Bundle\s+(\d+)\b", s)
        if not m:
            return None
        idx = int(m.group(1))
        return self.bundles[idx]

    def preview_bundle(self):
        b = self.selected_bundle()
        if not b:
            messagebox.showinfo("Preview", "No bundle selected.")
            return
        idx, off, _ = b
        sub = CHARA_BROWSER / f"bundle_{idx:03d}_off_{off:08x}"
        idx_html = sub / "index.html"
        if idx_html.exists():
            webbrowser.open(idx_html.as_uri())
        else:
            messagebox.showwarning("Preview", f"No textures for bundle {idx}.\nLooked in: {sub}")

    def open_map(self):
        webbrowser.open((CHARA_BROWSER / "index.html").as_uri())

    def _build_pnach(self):
        write_pnach(
            bundle=self.selected_bundle(),
            hp_lock=self.hp_lock.get(),
            no_blur=self.no_blur.get(),
            no_letterbox=self.no_letterbox.get(),
            voice_code=VOICE_PRESETS[self.voice_var.get()],
        )

    def apply_only(self):
        self._build_pnach()
        self.log(f"✓ pnach written: {PNACH_FILE}")

    def revert(self):
        try:
            PNACH_FILE.unlink()
            self.log("✓ pnach removed (vanilla game)")
        except FileNotFoundError:
            self.log("(pnach was already absent)")

    def apply_and_launch(self):
        self._build_pnach()
        self.log(f"✓ pnach written")
        killed = kill_daemons()
        if killed:
            self.log(f"✓ killed daemons: {', '.join(killed)}")
        if not self.iso_path:
            messagebox.showerror("Launch", "Tenchu ISO not found; edit ISO constant in tenchu_launcher.py")
            return
        if not PCSX2.exists():
            messagebox.showerror("Launch", f"PCSX2 not at {PCSX2}")
            return
        threading.Thread(target=launch_pcsx2, args=(self.iso_path,), daemon=True).start()
        self.log(f"▶ launching PCSX2 with {self.iso_path.name}")


if __name__ == "__main__":
    App().mainloop()
